In [3]:
import numpy as np
import matplotlib.pyplot as plt


In [4]:
x_train = np.array([[952,2,1,65],[1244,3,2,64],[1947,3,2,17]])
y_train = np.array([271.5,232,509.8])
x_features = ['size(sqft)','bedrooms','floors','age']

In [5]:
def compute_gradient(x,y,w,b):
    m,n = x.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.
    for i in range (m):
        err = (np.dot(w,x[i]) + b) - y[i]
        for j in range (n):
            dj_dw[j] = dj_dw[j] +  (err*x[i,j])
        dj_db = dj_db + err
    dj_dw = dj_dw/ m
    dj_db = dj_db/m
    return dj_dw , dj_db

In [6]:
def gradient_descent(x,y,w_in,b_in,gradient_function,alpha,num_iters):
    w = w_in
    b = b_in
    for i in range(num_iters):
        dj_dw , dj_db = gradient_function(x,y,w,b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db
    return w , b

In [7]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [8]:
alpha = 1e-7
w_final , b_final = gradient_descent(x_train,y_train,w_init,b_init,compute_gradient,alpha,10)

In [9]:
print(w_final , b_final)

[  0.48230089  18.75427557 -53.36007373 -26.39441034] 785.1813941620888


In [10]:
def zscore_normalized_features(X):
    mu = np.mean(X,axis = 0)
    sigma = np.std(X,axis  = 0)
    x_norm = (X - mu)/sigma
    return mu,sigma,x_norm

In [11]:
x_mu , x_sigma,x_norm = zscore_normalized_features(x_train)
print(x_mu , x_sigma,x_norm)

[1381.            2.66666667    1.66666667   48.66666667] [417.59869093   0.47140452   0.47140452  22.39543604] [[-1.02730207 -1.41421356 -1.41421356  0.72931526]
 [-0.32806616  0.70710678  0.70710678  0.68466331]
 [ 1.35536823  0.70710678  0.70710678 -1.41397857]]


In [18]:
alpha = 1e-7
w_norm , b_norm = gradient_descent(x_norm,y_train,w_init,b_init,compute_gradient,alpha,10)

In [19]:
print(w_final , b_final)

[  0.39144662  18.75383496 -53.36025698 -26.42142856] 785.1806893851394


In [21]:
x_house = np.array([1200,3,1,40])
x_house_norm = (x_house - x_mu)/x_sigma
print(x_house_norm)
x_house_predict = np.dot(x_house_norm,w_norm) + b_norm
print(x_house_predict)

[-0.43343048  0.70710678 -1.41421356 -0.38698361]
883.9594472528117
